In [1]:
import pandas as pd
import numpy as np
import os
import cv2

In [2]:
os.getcwd()

'C:\\Users\\ravin'

In [3]:
os.chdir(r"C:\Users\ravin\Desktop\train")

In [4]:
os.getcwd()

'C:\\Users\\ravin\\Desktop\\train'

In [5]:
all_images=os.listdir(r"C:\Users\ravin\Desktop\train")

In [6]:
new_list1=[]
new_list2=[]
for i in all_images:
    if i.startswith("c"):
        new_list1.append(i)
    elif i.startswith("d"):
        new_list2.append(i)

In [7]:
os.mkdir(r"C:\Users\ravin\Desktop\cat_train")

In [8]:
os.mkdir(r"C:\Users\ravin\Desktop\dog_train")

In [9]:
count=0
for y in all_images:
    count=count+1
    if y.startswith("cat"):
        img=cv2.imread(r"C:\Users\ravin\Desktop\train\{}".format(y))
        cv2.imwrite(r"C:\Users\ravin\Desktop\cat_train\{}.jpg". format(count),img)
    else:
        img1=cv2.imread(r"C:\Users\ravin\Desktop\train\{}".format(y))
        cv2.imwrite(r"C:\Users\ravin\Desktop\dog_train\{}.jpg". format(count),img1)

In [11]:
os.chdir(r"C:\Users\ravin\Desktop\cat_train")
all_images=os.listdir()
cat=[]
for i in all_images:
    img1=cv2.imread(r"C:\Users\ravin\Desktop\cat_train\\"+i)
    grey=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY) #changing colorspace
    resized=cv2.resize(grey,(150,100))  #here am reducing the pixels
    f_cat=resized.flatten().tolist()
    cat.append(f_cat)

In [12]:
cat_data=pd.DataFrame(cat)
cat_data["label"]="cat"

In [13]:
cat_data

,0,1,2,3,4,5,6,7,8,9,...,14991,14992,14993,14994,14995,14996,14997,14998,14999,label
0,167,172,173,176,180,182,184,186,188,190,...,2,2,2,2,2,2,2,2,2,cat
1,77,81,77,75,79,80,71,73,68,73,...,184,183,183,181,177,174,166,164,164,cat
2,197,198,201,201,201,201,201,199,199,200,...,236,235,232,228,225,223,227,232,234,cat
3,145,88,86,131,133,137,144,135,130,144,...,73,87,79,90,89,68,95,74,68,cat
4,37,72,99,120,135,142,146,135,118,129,...,32,32,31,28,27,29,34,30,31,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,79,101,118,105,62,99,116,114,71,99,...,200,198,196,208,201,195,192,174,176,cat
12496,184,184,200,197,187,176,169,160,153,146,...,155,127,113,96,92,84,79,70,65,cat
12497,66,68,29,31,30,29,29,28,28,28,...,35,34,31,31,28,28,27,26,22,cat
12498,99,101,101,100,103,106,106,114,110,108,...,160,159,150,151,154,153,154,152,143,cat
12499,155,141,130,101,79,69,100,130,152,167,...,239,240,230,236,237,216,240,238,241,cat

In [15]:
os.chdir(r"C:\Users\ravin\Desktop\dog_train")
all_images=os.listdir()
dog=[]
for dog_images in all_images:
    img1=cv2.imread(r"C:\Users\ravin\Desktop\dog_train\\"+dog_images)
    grey=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
    resize_=cv2.resize(grey,(150,150))
    f_dog=resize_.flatten().tolist()
    dog.append(f_dog)

In [16]:
dog_data=pd.DataFrame(dog)
dog_data["label"]="dog"